config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new' 
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :favorites, only: [:create, :destroy]
  resources :pictures do
    collection do
      post :confirm
      get :bookmarks
    end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :picture, presence: true
  validates :content, presence: true
  mount_uploader :picture, PictureUploader
  has_many :favorites, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true , length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, length: { minimum: 6 }, on: :create
  mount_uploader :image, ImageUploader
  before_validation { email.downcase! }
  has_secure_password
  has_many :pictures
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @pictures = Picture.all
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else @picture = Picture.new
    end
  end

  def confirm
    @picture = Picture.new(picture_params)
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if @picture.save
      PictureMailer.contact_mail(@picture).deliver
      redirect_to pictures_path
    else
      render :new
    end
  end

  def edit
    @picture = Picture.find(params[:id])
    if @picture.user_id != current_user.id
      redirect_to new_session_path
    end
  end

  def update
    @picture = Picture.find(params[:id])
    if @picture.user_id != current_user.id
      redirect_to new_session_path
    end

    if @picture.update(picture_params)
      redirect_to pictures_path
    else
      render :edit
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    if @picture.user_id != current_user.id
      redirect_to new_session_path
    end
    @picture.destroy
    redirect_to pictures_path
  end

  def bookmarks
    @pictures = current_user.favorites
  end

  private

  def picture_params
    params.require(:picture).permit(:content, :picture, :picture_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to new_session_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to new_session_path
    end
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,:image, :image_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Telegram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <<body>
    <header class = 'header'>
      <ul class = "clearfix">
        <% if logged_in? %>
          <li class = "header_menu"><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
          <li class = "header_menu"><%= link_to "Profile", user_path(current_user.id) %></li>
        <% else %>
          <li class = "header_menu"><%= link_to "Sign up", new_user_path %></li>
          <li class = "header_menu"><%= link_to "Login", new_session_path %></li>
        <% end %>
      </ul>
    </header>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
      <%= yield %>
  <footer>
  </footer>
  </body>
</html>

app/views/pictures/bookmarks.html.erb
<h1>お気に入り一覧</h1>

<table>
  <tr>
    <th>内容</th>
    <th>投稿者</th>
  </tr>

  <% @pictures.each do |pct| %>
    <% bookmark = Picture.find_by(id: pct.picture_id) %>
    <tr>
      <td><%= bookmark.content %></td>
      <td><%= "#{bookmark.user.name}" %></td>
      <td><%= link_to '詳細', picture_path(bookmark.id) %></td>
    </tr>
  <% end %>
</table>

app/views/pictures/confirm.html.erb
<h1>確認画面</h1>
<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <p>本文:<%= @picture.content %></p>
  <%= image_tag(@picture.picture.url) if @picture.picture && @picture.picture.url %>
  <%= form.hidden_field :picture_cache %>
  <%= form.submit "投稿する" %>
<% end %>

<%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/pictures/edit.html.erb
<%= form_with(model: @picture, local: true) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="picture_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="picture_picture">
    <%= form.label :picture %>
    <%= form.text_field :picture %>
  </div>
  <%= form.submit %>
<% end %>

app/views/pictures/index.html.erb
<br>
<h1>〜Telegram〜</h1>
<br>
<div class = 'top_menu'>
  <p>-ようこそ！　<%= "#{current_user.name}" %>さん-</p>
  <p><%= link_to '投稿する', new_picture_path, class: "btn btn-info" %></p>
  <p><%= link_to 'お気に入り一覧', bookmarks_pictures_path, class: "btn btn-info" %></p>
</div>

<% @pictures.each do |pct| %>
  <ul class = "event clearfix">
    <li><%= pct.content %></li>
    <li><%= image_tag pct.picture.url %></li>
    <div class = "clearfix menu">
      <% unless pct.user_id == current_user.id %>
        <% @favorite = current_user.favorites.find_by(picture_id: pct.id) %>
        <% if @favorite.present? %>
          <li class = "item"><%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %></li>
        <% else %>
        <li class = "item"><%= link_to 'お気に入りする', favorites_path(picture_id: pct.id), method: :post, class: 'btn btn-primary' %></li>
        <% end %>
      <% end %>
      <div class = 'center'>
        <li class = "item"><%= link_to '詳細', picture_path(pct.id), class: 'btn btn-success' %></li>
        <% if current_user.id == pct.user.id %>
          <li class = "item"><%= link_to '編集', edit_picture_path(pct.id), class: "btn btn-success" %></li>
          <li class = "item"><%= link_to '削除', picture_path(pct.id), method: :delete, data: { confirm: '本当に削除していいですか？' }, class: "btn btn-success" %></li>
        <% end %>
      </div>
      <li class = 'sentence'>(<%= "#{pct.user.name}" %>の投稿)</li>
    </div>
  </ul>
<% end %>
</table>
<br>
<br>

app/views/pictures/new.html.erb
<%= form_with(model: @picture, local: true, url:confirm_pictures_path) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="picture_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="picture_picture">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>
  <%= form.submit %>
<% end %>

app/views/pictures/show.html.erb
<h1>詳細画面</h1>
<p>内容: <%= @picture.content %></p>
<p>
  <strong>Image:</strong>
  <%= image_tag @picture.picture.url %>
</p>

app/views/users/edit.html.erb
 <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= @user.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  
  <%= f.label :image %>
  <%= f.file_field :image %>

  <%= f.submit "登録する" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= @user.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.label :image %>
  <%= f.file_field :image %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<% if @user[:image] %>
  <p>プロフィール画像　　<%= image_tag @user.image.url %></p>
<% end %>

<p><%= link_to "ユーザー画像を編集する", edit_user_path(@user.id) %></p>
<p><%= link_to "Telegramのページへ行く", pictures_path %>